Repository scylladb/scylla-rust-driver, pull requests merged in 2023-08, with the labels that each got.

#775 default_policy: Builder: forbid preferring rack without specifing datacenter
  docs/source/load-balancing/default-policy.md
  scylla/src/transport/load_balancing/default.rs
Labels: API-breaking

#773 codewide: Decrease excessive visibility from `pub` - nonbreaking changes
  scylla/src/transport/caching_session.rs
  scylla/src/transport/cluster.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/connection_pool.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/node.rs
  scylla/src/transport/topology.rs
  scylla/src/utils/parse.rs
  scylla/src/utils/pretty.rs
Labels: API-stability

#777 default policy: Rack awareness without token awareness
  docs/source/load-balancing/default-policy.md
  scylla/src/transport/load_balancing/default.rs
  scylla/src/transport/locator/mod.rs
Labels: load-balancing, API-breaking

#784 doc: enable publishing docs for tag v0.9.0
  docs/source/conf.py
Labels: documentation

#783 doc: replace python3 with python in Makefile
  docs/Makefile
Labels: documentation

#758 Stateful partitioners
  examples/compare-tokens.rs
  scylla-cql/src/frame/response/result.rs
  scylla/benches/benchmark.rs
  scylla/src/statement/prepared_statement.rs
  scylla/src/transport/cluster.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/partitioner.rs
  scylla/src/transport/session.rs
  scylla/src/transport/session_test.rs
  scylla/src/utils/mod.rs
Labels: performance

#780 cluster: small performance optimisations
  scylla/src/transport/cluster.rs
  scylla/src/transport/session.rs
  scylla/src/transport/topology.rs
Labels: performance

#796 session: add docstrings for AddressTranslator
  scylla/src/transport/session.rs
Labels: documentation
