Repository scylladb/scylla-rust-driver, pull requests merged in 2024-05, with the labels that each got.

#985 derive `FromRow` for structs with unnamed fields
  scylla-cql/src/frame/response/cql_to_rust.rs
  scylla-macros/src/from_row.rs
  scylla-macros/src/parser.rs
  scylla/src/macros.rs
Labels: enhancement, proc-macros

#937 Introduce support for Tablets
  .github/workflows/rust.yml
  .github/workflows/tablets.yml
  Cargo.lock.msrv
  Makefile
  examples/compare-tokens.rs
  scylla-cql/src/frame/mod.rs
  scylla-cql/src/frame/protocol_features.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/frame/value_tests.rs
  scylla-cql/src/types/serialize/row.rs
  scylla/Cargo.toml
  scylla/src/statement/prepared_statement.rs
  scylla/src/transport/caching_session.rs
  scylla/src/transport/cluster.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/connection_pool.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/load_balancing/default.rs
  scylla/src/transport/load_balancing/mod.rs
  scylla/src/transport/load_balancing/plan.rs
  scylla/src/transport/locator/mod.rs
  scylla/src/transport/locator/tablets.rs
  scylla/src/transport/locator/test.rs
  scylla/src/transport/node.rs
  scylla/src/transport/query_result.rs
  scylla/src/transport/session.rs
  scylla/src/transport/session_test.rs
  scylla/src/utils/test_utils.rs
  scylla/tests/integration/consistency.rs
  scylla/tests/integration/main.rs
  scylla/tests/integration/shards.rs
  scylla/tests/integration/tablets.rs
Labels: semver-checks-breaking

#980 docs: adding context to timeuuid using v1 feature
  Cargo.lock.msrv
  docs/source/data-types/timeuuid.md
  examples/Cargo.toml
Labels: documentation

#997 CONTIBUTING.md: update maintainers list
  CONTRIBUTING.md
Labels: documentation

#986 prepared: docs for `PreparedStatement`
  docs/source/queries/prepared.md
  scylla/src/statement/prepared_statement.rs
  scylla/src/transport/session.rs
Labels: documentation

#1004 Pre-deserialization-refactor preparatory changes
  Cargo.lock.msrv
  scylla-cql/Cargo.toml
  scylla-cql/src/frame/types.rs
  scylla-cql/src/frame/value_tests.rs
  scylla-cql/src/types/serialize/row.rs
  scylla-cql/src/types/serialize/value.rs
  scylla-macros/Cargo.toml
  scylla-proxy/Cargo.toml
  scylla/Cargo.toml
  scylla/src/history.rs
  scylla/src/transport/query_result.rs
Labels: semver-checks-breaking
