Repository scylladb/scylla-rust-driver, pull requests merged in 2024-11, with the labels that each got.

#1093 Introduce new deserialization framework upper layer abstractions
  Cargo.lock.msrv
  examples/cqlsh-rs.rs
  examples/tower.rs
  examples/tracing.rs
  scylla-cql/Cargo.toml
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/frame/types.rs
  scylla-cql/src/types/deserialize/mod.rs
  scylla-cql/src/types/deserialize/result.rs
  scylla/src/lib.rs
  scylla/src/transport/caching_session.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/errors.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/large_batch_statements_test.rs
  scylla/src/transport/legacy_query_result.rs
  scylla/src/transport/mod.rs
  scylla/src/transport/query_result.rs
  scylla/src/transport/session.rs
  scylla/src/transport/session_test.rs
  scylla/tests/integration/tablets.rs
Labels: semver-checks-breaking, area/deserialization

#1120 Migrate tablets to new deserialization framework
  scylla-cql/src/frame/mod.rs
  scylla-cql/src/frame/types.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/locator/tablets.rs
Labels: area/deserialization

#1122 iterator: delete `TypedRowLendingStream` as unusable
  scylla/src/transport/iterator.rs
Labels: semver-checks-breaking, area/deserialization

#1124 spec_exec: fix can_be_ignored function
  scylla/src/transport/speculative_execution.rs
Labels: bug

#1117 errors: replace `RowsParseError` and narrow the return types after deserialization refactor
  docs/source/queries/paged.md
  docs/source/queries/result.md
  docs/source/queries/simple.md
  examples/compare-tokens.rs
  examples/cqlsh-rs.rs
  examples/custom_deserialization.rs
  examples/get_by_name.rs
  examples/select-paging.rs
  examples/tower.rs
  scylla-cql/src/frame/frame_errors.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/types/deserialize/row.rs
  scylla-cql/src/types/deserialize/value.rs
  scylla/src/lib.rs
  scylla/src/transport/caching_session.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/cql_collections_test.rs
  scylla/src/transport/cql_types_test.rs
  scylla/src/transport/cql_value_test.rs
  scylla/src/transport/errors.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/legacy_query_result.rs
  scylla/src/transport/load_balancing/default.rs
  scylla/src/transport/query_result.rs
  scylla/src/transport/session.rs
  scylla/src/transport/session_test.rs
  scylla/src/transport/silent_prepare_batch_test.rs
  scylla/src/transport/speculative_execution.rs
  scylla/src/transport/topology.rs
  scylla/src/utils/test_utils.rs
  scylla/tests/integration/skip_metadata_optimization.rs
Labels: semver-checks-breaking, area/deserialization

#1121 Aid in migration to the new deserialization API
  docs/source/SUMMARY.md
  docs/source/migration-guides/0.15-deserialization.md
  docs/source/migration-guides/migration-guides.md
  scylla-cql/src/frame/response/cql_to_rust.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/lib.rs
  scylla/src/lib.rs
  scylla/src/macros.rs
  scylla/src/transport/caching_session.rs
  scylla/src/transport/cluster.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/legacy_query_result.rs
  scylla/src/transport/query_result.rs
  scylla/src/transport/session.rs
  scylla/src/transport/session_builder.rs
  scylla/src/transport/session_test.rs
  scylla/tests/integration/hygiene.rs
Labels: semver-checks-breaking, area/deserialization

#1119 Unify macro attributes between serialization and deserialization derive macros
  docs/source/data-types/udt.md
  docs/source/migration-guides/0.11-serialization.md
  scylla-cql/src/types/deserialize/mod.rs
  scylla-cql/src/types/deserialize/row.rs
  scylla-cql/src/types/deserialize/row_tests.rs
  scylla-cql/src/types/deserialize/value.rs
  scylla-cql/src/types/deserialize/value_tests.rs
  scylla-cql/src/types/mod.rs
  scylla-cql/src/types/serialize/row.rs
  scylla-cql/src/types/serialize/value.rs
  scylla-cql/src/types/types_tests.rs
  scylla-macros/src/deserialize/row.rs
  scylla-macros/src/deserialize/value.rs
  scylla-macros/src/lib.rs
  scylla-macros/src/serialize/mod.rs
  scylla-macros/src/serialize/row.rs
  scylla-macros/src/serialize/value.rs
  scylla/src/macros.rs
Labels: area/proc-macros, area/deserialization

#1020 cassandra 5.0 vector type CREATE/INSERT support
  .github/workflows/cassandra.yml
  scylla/Cargo.toml
  scylla/src/transport/session_test.rs
  scylla/src/transport/topology.rs
  scylla/src/utils/parse.rs
Labels: semver-checks-breaking

#1123 Update time docs to reflect new chrono feature flag name
  docs/source/data-types/date.md
  docs/source/data-types/time.md
  docs/source/data-types/timestamp.md
Labels: area/documentation
