Repository scylladb/scylla-rust-driver, pull requests merged in 2024-08, with the labels that each got.

#1045 topology: skip invalid peers instead of failing
  scylla/src/transport/topology.rs
Labels: metadata

#1039 connection: expose setters for STARTUP options
  scylla-cql/src/frame/mod.rs
  scylla-cql/src/frame/protocol_features.rs
  scylla-cql/src/frame/request/options.rs
  scylla-cql/src/frame/request/startup.rs
  scylla-cql/src/frame/types.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/mod.rs
  scylla/src/transport/session.rs
  scylla/src/transport/session_builder.rs
  scylla/tests/integration/main.rs
  scylla/tests/integration/self_identity.rs
Labels: enhancement, cpp-rust-driver-p0

#1024 Deserialization derive macros
  scylla-cql/src/lib.rs
  scylla-cql/src/types/deserialize/mod.rs
  scylla-cql/src/types/deserialize/row.rs
  scylla-cql/src/types/deserialize/row_tests.rs
  scylla-cql/src/types/deserialize/value.rs
  scylla-cql/src/types/deserialize/value_tests.rs
  scylla-macros/src/deserialize/mod.rs
  scylla-macros/src/deserialize/row.rs
  scylla-macros/src/deserialize/value.rs
  scylla-macros/src/lib.rs
  scylla-macros/src/parser.rs
  scylla/src/macros.rs
Labels: enhancement, performance, semver-checks-breaking, deserialization

#1063 result: fix bug: paging state taken from PREPARED response instead of RESULT
  scylla-cql/src/frame/response/result.rs
  scylla/tests/integration/skip_metadata_optimization.rs
Labels: bug

#1026 errors: Replace `ParseError` with `CqlResponseParseError` in `frame::response` module
  scylla-cql/src/errors.rs
  scylla-cql/src/frame/frame_errors.rs
  scylla-cql/src/frame/response/authenticate.rs
  scylla-cql/src/frame/response/error.rs
  scylla-cql/src/frame/response/event.rs
  scylla-cql/src/frame/response/mod.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/frame/response/supported.rs
  scylla-cql/src/frame/server_event_type.rs
  scylla/src/transport/load_balancing/default.rs
Labels: semver-checks-breaking

#1062 default_lb: Enrich comments & docstrings
  scylla/src/transport/load_balancing/default.rs
  scylla/src/transport/locator/mod.rs
Labels: documentation, load-balancing

#1065 New deserialization API - preparations
  scylla-cql/src/errors.rs
  scylla-cql/src/frame/frame_errors.rs
  scylla-cql/src/frame/request/query.rs
  scylla-cql/src/frame/response/mod.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/types/deserialize/result.rs
  scylla-cql/src/types/deserialize/value.rs
  scylla-cql/src/types/deserialize/value_tests.rs
  scylla/src/lib.rs
  scylla/src/statement/prepared_statement.rs
  scylla/src/transport/caching_session.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/query_result.rs
  scylla/src/transport/session_test.rs
Labels: semver-checks-breaking, deserialization
