Repository scylladb/scylla-rust-driver, pull requests merged in 2024-06, with the labels that each got.

#1000 Rename `SerializeCql` to `SerializeValue`
  docs/source/data-types/udt.md
  docs/source/migration-guides/0.11-serialization.md
  examples/user-defined-type.rs
  examples/value_list.rs
  scylla-cql/src/frame/value_tests.rs
  scylla-cql/src/lib.rs
  scylla-cql/src/types/serialize/mod.rs
  scylla-cql/src/types/serialize/row.rs
  scylla-cql/src/types/serialize/value.rs
  scylla-cql/src/types/serialize/writers.rs
  scylla-macros/src/lib.rs
  scylla-macros/src/serialize/mod.rs
  scylla-macros/src/serialize/row.rs
  scylla-macros/src/serialize/value.rs
  scylla/src/macros.rs
  scylla/src/transport/cql_collections_test.rs
  scylla/src/transport/cql_types_test.rs
  scylla/src/transport/locator/tablets.rs
  scylla/src/transport/session_test.rs
  scylla/tests/integration/hygiene.rs
Labels: semver-checks-breaking

#970 Deserialization refactor: introduce new deserialization traits
  scylla-cql/Cargo.toml
  scylla-cql/src/frame/frame_errors.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/types/deserialize/frame_slice.rs
  scylla-cql/src/types/deserialize/mod.rs
  scylla-cql/src/types/deserialize/result.rs
  scylla-cql/src/types/deserialize/row.rs
  scylla-cql/src/types/deserialize/value.rs
  scylla-cql/src/types/mod.rs
  scylla/src/lib.rs
Labels: performance, semver-checks-breaking

#939 Rename `chrono`, `time` and `secret` features
  .github/workflows/rust.yml
  Cargo.lock.msrv
  examples/Cargo.toml
  scylla-cql/Cargo.toml
  scylla-cql/src/frame/response/cql_to_rust.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/frame/value.rs
  scylla-cql/src/frame/value_tests.rs
  scylla-cql/src/types/deserialize/value.rs
  scylla-cql/src/types/serialize/value.rs
  scylla/Cargo.toml
  scylla/src/transport/cql_types_test.rs
Labels: API-stability, semver-checks-breaking
