Repository scylladb/scylla-rust-driver, pull requests merged in 2024-12, with the labels that each got.

#1133 rows_result: implement into_inner behind `cpp_rust_unstable` cfg
  .github/workflows/rust.yml
  scylla/Cargo.toml
  scylla/src/lib.rs
  scylla/src/transport/query_result.rs
Labels: cpp-rust-driver-p0

#1142 Make RawBatchValuesIteratorAdapter length equal to its internal BatchValuesIter length
  scylla-cql/src/types/serialize/raw_batch.rs
  scylla/tests/integration/batch.rs
  scylla/tests/integration/main.rs
Labels: bug

#1141 Deprecate legacy items
  Cargo.lock.msrv
  scylla-cql/Cargo.toml
  scylla-cql/src/frame/response/cql_to_rust.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/frame/value.rs
  scylla-cql/src/frame/value_tests.rs
  scylla-cql/src/lib.rs
  scylla-cql/src/types/serialize/batch.rs
  scylla-cql/src/types/serialize/row.rs
  scylla-cql/src/types/serialize/value.rs
  scylla-proxy/Cargo.toml
  scylla/Cargo.toml
  scylla/src/lib.rs
  scylla/src/macros.rs
  scylla/src/transport/errors.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/legacy_query_result.rs
  scylla/src/transport/load_balancing/default.rs
  scylla/src/transport/session.rs
  scylla/src/transport/speculative_execution.rs
Labels: API-stability, semver-checks-breaking

#1149 Remove uses of `SerializeValuesError` and deprecate it
  scylla-cql/src/frame/value.rs
  scylla-cql/src/types/serialize/mod.rs
  scylla-cql/src/types/serialize/row.rs
  scylla/src/transport/errors.rs
Labels: API-stability, semver-checks-breaking

#1148 value: `Cql[Varint/Decimal]Borrowed`
  docs/source/data-types/decimal.md
  docs/source/data-types/varint.md
  scylla-cql/src/frame/value.rs
  scylla-cql/src/types/deserialize/value.rs
  scylla-cql/src/types/deserialize/value_tests.rs
  scylla-cql/src/types/serialize/value.rs
Labels: cpp-rust-driver-p0, area/deserialization
