Repository scylladb/scylla-rust-driver, pull requests merged in 2024-09, with the labels that each got.

#1068 docs: Eradicate unpaged SELECTs and warn about their drawbacks
  README.md
  docs/source/data-types/blob.md
  docs/source/data-types/collections.md
  docs/source/data-types/counter.md
  docs/source/data-types/date.md
  docs/source/data-types/decimal.md
  docs/source/data-types/duration.md
  docs/source/data-types/inet.md
  docs/source/data-types/primitive.md
  docs/source/data-types/text.md
  docs/source/data-types/time.md
  docs/source/data-types/timestamp.md
  docs/source/data-types/timeuuid.md
  docs/source/data-types/tuple.md
  docs/source/data-types/udt.md
  docs/source/data-types/uuid.md
  docs/source/data-types/varint.md
  docs/source/queries/paged.md
  docs/source/queries/queries.md
  docs/source/queries/result.md
  docs/source/queries/simple.md
  docs/source/quickstart/example.md
Labels: documentation, statement-execution

#1067 errors: refactor error types on a connection level
  scylla-cql/src/errors.rs
  scylla-cql/src/frame/frame_errors.rs
  scylla-cql/src/frame/response/mod.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/connection_pool.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/load_balancing/default.rs
  scylla/src/transport/node.rs
  scylla/src/transport/session.rs
Labels: semver-checks-breaking

#1075 errors: fix driver's logic that bases on error variants returned from query execution
  scylla/src/transport/cluster.rs
  scylla/src/transport/connection_pool.rs
  scylla/src/transport/downgrading_consistency_retry_policy.rs
  scylla/src/transport/errors.rs
  scylla/src/transport/load_balancing/default.rs
  scylla/src/transport/retry_policy.rs
  scylla/src/transport/speculative_execution.rs
Labels: bug, semver-checks-breaking

#1054 errors: remove ParseError
  scylla-cql/src/frame/frame_errors.rs
  scylla-cql/src/frame/mod.rs
  scylla-cql/src/frame/request/auth_response.rs
  scylla-cql/src/frame/request/batch.rs
  scylla-cql/src/frame/request/execute.rs
  scylla-cql/src/frame/request/mod.rs
  scylla-cql/src/frame/request/options.rs
  scylla-cql/src/frame/request/prepare.rs
  scylla-cql/src/frame/request/query.rs
  scylla-cql/src/frame/request/register.rs
  scylla-cql/src/frame/request/startup.rs
  scylla-cql/src/frame/response/cql_to_rust.rs
  scylla-cql/src/frame/types.rs
  scylla-cql/src/frame/value.rs
  scylla-cql/src/types/deserialize/mod.rs
  scylla-cql/src/types/serialize/row.rs
  scylla-proxy/src/errors.rs
  scylla-proxy/src/frame.rs
  scylla-proxy/src/proxy.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/errors.rs
  scylla/src/transport/load_balancing/default.rs
Labels: semver-checks-breaking
