Repository scylladb/scylla-rust-driver, pull requests merged in 2024-10, with the labels that each got.

#1077 Fix clippy `expect_used` complains for `derive(FromRow)` macro
  scylla-cql/src/frame/response/cql_to_rust.rs
  scylla-macros/src/from_row.rs
Labels: semver-checks-breaking

#1080 errors: protocol error refactor
  scylla/src/statement/prepared_statement.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/downgrading_consistency_retry_policy.rs
  scylla/src/transport/errors.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/load_balancing/default.rs
  scylla/src/transport/retry_policy.rs
  scylla/src/transport/session.rs
  scylla/src/transport/speculative_execution.rs
  scylla/src/transport/topology.rs
Labels: semver-checks-breaking

#1082 make `ResultMetadata` lifetime-generic
  scylla-cql/src/frame/frame_errors.rs
  scylla-cql/src/frame/response/mod.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/frame/value_tests.rs
  scylla-cql/src/types/deserialize/mod.rs
  scylla-cql/src/types/deserialize/result.rs
  scylla-cql/src/types/deserialize/row.rs
  scylla-cql/src/types/deserialize/row_tests.rs
  scylla-cql/src/types/deserialize/value.rs
  scylla-cql/src/types/deserialize/value_tests.rs
  scylla-cql/src/types/serialize/row.rs
  scylla-cql/src/types/serialize/value.rs
  scylla-macros/src/deserialize/row.rs
  scylla-macros/src/deserialize/value.rs
  scylla-macros/src/serialize/row.rs
  scylla-macros/src/serialize/value.rs
  scylla/src/statement/prepared_statement.rs
  scylla/src/transport/caching_session.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/locator/tablets.rs
  scylla/src/transport/query_result.rs
  scylla/src/transport/session.rs
  scylla/src/transport/session_test.rs
Labels: semver-checks-breaking, deserialization

#1087 errors: expose pub getters for type-erased errors
  scylla-cql/src/types/deserialize/mod.rs
  scylla-cql/src/types/serialize/mod.rs
  scylla/src/transport/connection.rs
  scylla/src/transport/errors.rs
Labels: semver-checks-breaking

#1090 scylla/lib.rs: Remove stars in serialization frameworks imports
  scylla-cql/src/types/serialize/batch.rs
  scylla-cql/src/types/serialize/row.rs
  scylla-cql/src/types/serialize/value.rs
  scylla-cql/src/types/serialize/writers.rs
  scylla/src/lib.rs
Labels: API-stability

#1092 keepalive: trace in case of success
  scylla/src/transport/connection.rs
Labels: cpp-rust-driver-p1

#1094 Fix unnamable types
  scylla-cql/Cargo.toml
  scylla-macros/Cargo.toml
  scylla/Cargo.toml
  scylla/src/cloud/mod.rs
  scylla/src/lib.rs
  scylla/src/transport/cluster.rs
  scylla/src/transport/node.rs
  scylla/src/transport/session.rs
  scylla/src/transport/session_builder.rs
  scylla/src/transport/session_test.rs
  scylla/src/transport/topology.rs
Labels: semver-checks-breaking

#1103 retry_policy: replace all usages of `Box<dyn RetryPolicy>` with `Arc<...>`
  docs/source/execution-profiles/maximal-example.md
  docs/source/retry-policy/default.md
  docs/source/retry-policy/downgrading-consistency.md
  docs/source/retry-policy/fallthrough.md
  examples/execution_profile.rs
  scylla/src/transport/downgrading_consistency_retry_policy.rs
  scylla/src/transport/execution_profile.rs
  scylla/src/transport/retry_policy.rs
  scylla/src/transport/session_test.rs
  scylla/tests/integration/consistency.rs
  scylla/tests/integration/execution_profiles.rs
  scylla/tests/integration/lwt_optimisation.rs
  scylla/tests/integration/retries.rs
Labels: semver-checks-breaking

#1101 Parametrize `Deserialize{Value,Row}` with two lifetimes: `'frame` and `'metadata` separately
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/types/deserialize/mod.rs
  scylla-cql/src/types/deserialize/result.rs
  scylla-cql/src/types/deserialize/row.rs
  scylla-cql/src/types/deserialize/row_tests.rs
  scylla-cql/src/types/deserialize/value.rs
  scylla-cql/src/types/deserialize/value_tests.rs
  scylla-macros/src/deserialize/mod.rs
  scylla-macros/src/deserialize/row.rs
  scylla-macros/src/deserialize/value.rs
Labels: API-breaking, area/deserialization

#1109 result: fix wrong implied lifetime in `col_specs()`
  scylla-cql/src/frame/response/result.rs
  scylla/src/statement/prepared_statement.rs
  scylla/src/transport/iterator.rs
  scylla/src/transport/query_result.rs
Labels: bug
