Repository scylladb/scylla-rust-driver, pull requests merged in 2025-03, with the labels that each got.

#1252 Remove SerializedValues from public API of `scylla` crate.
  scylla-cql/src/serialize/row.rs
  scylla/Cargo.toml
  scylla/benches/benchmark.rs
  scylla/src/client/session_test.rs
  scylla/src/cluster/metadata.rs
  scylla/src/cluster/state.rs
  scylla/src/errors.rs
  scylla/src/lib.rs
  scylla/src/routing/partitioner.rs
Labels: semver-checks-breaking

#1260 Address unnecessary doc(hidden)
  Cargo.lock.msrv
  docs/source/data-types/udt.md
  docs/source/statements/result.md
  examples/custom_deserialization.rs
  examples/user-defined-type.rs
  scylla-cql/Cargo.toml
  scylla-cql/src/deserialize/mod.rs
  scylla-cql/src/deserialize/row.rs
  scylla-cql/src/deserialize/value.rs
  scylla-cql/src/frame/request/query.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/lib.rs
  scylla-cql/src/serialize/row_tests.rs
  scylla-cql/src/serialize/value_tests.rs
  scylla-cql/src/value.rs
  scylla-macros/Cargo.toml
  scylla-macros/src/lib.rs
  scylla-proxy/src/proxy.rs
  scylla/Cargo.toml
  scylla/src/client/session.rs
  scylla/src/cluster/metadata.rs
  scylla/src/lib.rs
  scylla/src/macros.rs
  scylla/src/observability/tracing.rs
  scylla/src/routing/locator/tablets.rs
  scylla/tests/integration/hygiene.rs
  scylla/tests/integration/utils.rs
Labels: semver-checks-breaking

#1262 Minor API stabilization changes
  scylla/src/lib.rs
  scylla/src/statement/batch.rs
  scylla/src/statement/prepared.rs
Labels: semver-checks-breaking

#1261 mark metadata public structs as `non_exhaustive`
  scylla/src/cluster/metadata.rs
Labels: semver-checks-breaking

#1266 state: Adjust ClusterState keyspace info getters
  docs/source/schema/schema.md
  scylla/src/client/session_test.rs
  scylla/src/cluster/state.rs
  scylla/src/policies/load_balancing/default.rs
  scylla/tests/integration/utils.rs
Labels: semver-checks-breaking

#1263 Make metrics collection optional/faster
  .github/workflows/rust.yml
  Cargo.lock.msrv
  docs/source/metrics/metrics.md
  docs/source/speculative-execution/percentile.md
  examples/Cargo.toml
  examples/basic.rs
  scylla/Cargo.toml
  scylla/src/client/pager.rs
  scylla/src/client/session.rs
  scylla/src/cluster/metadata.rs
  scylla/src/cluster/node.rs
  scylla/src/cluster/state.rs
  scylla/src/cluster/worker.rs
  scylla/src/network/connection_pool.rs
  scylla/src/observability/metrics.rs
  scylla/src/observability/mod.rs
  scylla/src/policies/load_balancing/default.rs
  scylla/src/policies/speculative_execution.rs
  scylla/src/routing/locator/test.rs
Labels: semver-checks-breaking

#1269 Mark some policies-related structs as non_exhaustive
  scylla/src/policies/load_balancing/mod.rs
  scylla/src/policies/retry/retry_policy.rs
  scylla/src/policies/speculative_execution.rs
  scylla/tests/integration/consistency.rs
Labels: semver-checks-breaking

#1171 Metadata queries with configurable server-side timeouts
  scylla/src/client/session.rs
  scylla/src/client/session_builder.rs
  scylla/src/cluster/control_connection.rs
  scylla/src/cluster/metadata.rs
  scylla/src/cluster/mod.rs
  scylla/src/cluster/worker.rs
  scylla/src/network/connection.rs
  scylla/src/network/mod.rs
  scylla/src/routing/sharding.rs
  scylla/src/utils/test_utils.rs
  scylla/tests/integration/main.rs
  scylla/tests/integration/metadata_custom_timeouts.rs
Labels: area/metadata

#1297 Implement coalescing delay configuration
  scylla/src/client/mod.rs
  scylla/src/client/session.rs
  scylla/src/client/session_builder.rs
  scylla/src/network/connection.rs
  scylla/src/network/mod.rs
Labels: cpp-rust-driver-p1
