Repository scylladb/scylla-rust-driver, pull requests merged in 2025-04, with the labels that each got.

#1308 cluster/state: Fix missing zero-token nodes in nodes info
  scylla/src/cluster/state.rs
  scylla/src/cluster/worker.rs
  scylla/src/policies/load_balancing/plan.rs
Labels: bug

#1315 tests: udt deserialization with metadata present but value missing
  scylla-cql/src/types_tests.rs
Labels: area/deserialization, area/testing

#1317 feat: add MaybeUnset::from_option() to reduce boilerplate
  scylla-cql/src/serialize/value_tests.rs
  scylla-cql/src/value.rs
Labels: enhancement

#1322 MAINTENANCE.md: describe `scylla-cql` API considerations
  MAINTENANCE.md
Labels: area/documentation

#1327 metrics: fix the bug where percentiles would return bucket count
  scylla/src/observability/metrics.rs
Labels: bug

#1325 Fix shard out of range panic
  scylla/src/client/pager.rs
  scylla/src/client/session.rs
  scylla/src/network/connection_pool.rs
  scylla/src/policies/load_balancing/mod.rs
  scylla/tests/integration/default_policy.rs
  scylla/tests/integration/load_balancing.rs
  scylla/tests/integration/main.rs
Labels: bug

#1329 Construct `PreparedStatement` only where needed
  scylla/src/client/session.rs
  scylla/src/network/connection.rs
  scylla/src/response/mod.rs
  scylla/src/response/request_response.rs
Labels: performance

#1326 Enforce request coordinator
  docs/source/load-balancing/load-balancing.md
  examples/Cargo.toml
  examples/enforce_coordinator.rs
  scylla/src/client/pager.rs
  scylla/src/client/session.rs
  scylla/src/policies/load_balancing/mod.rs
  scylla/src/policies/load_balancing/single_target.rs
  scylla/src/statement/batch.rs
  scylla/src/statement/mod.rs
  scylla/src/statement/prepared.rs
  scylla/src/statement/unprepared.rs
  scylla/tests/integration/statement.rs
  scylla/tests/integration/tablets.rs
Labels: cpp-rust-driver-p1
