Repository scylladb/scylla-rust-driver, pull requests merged in 2025-02, with the labels that each got.

#1192 errors: remove BadQuery::Other variant
  scylla/src/errors.rs
Labels: API-stability, semver-checks-breaking

#1187 codewide: rename remnants of cluster data to state
  docs/source/schema/schema.md
  examples/compare-tokens.rs
  scylla/src/client/pager.rs
  scylla/src/client/session.rs
  scylla/src/client/session_test.rs
  scylla/src/cluster/state.rs
  scylla/src/cluster/worker.rs
  scylla/src/policies/load_balancing/default.rs
  scylla/src/policies/load_balancing/plan.rs
  scylla/src/utils/test_utils.rs
  scylla/tests/integration/tablets.rs
  scylla/tests/integration/utils.rs
Labels: semver-checks-breaking

#1193 errors: introduce PrepareError
  scylla/src/client/caching_session.rs
  scylla/src/client/session.rs
  scylla/src/cluster/state.rs
  scylla/src/errors.rs
Labels: API-stability, semver-checks-breaking

#1184 Remove legacy serialization and deserialization APIs
  docs/source/conf.py
  docs/source/data-types/udt.md
  docs/source/migration-guides/0.11-serialization.md
  docs/source/migration-guides/0.15-deserialization.md
  docs/source/queries/batch.md
  scylla-cql/src/frame/response/cql_to_rust.rs
  scylla-cql/src/frame/response/mod.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/frame/value.rs
  scylla-cql/src/frame/value_tests.rs
  scylla-cql/src/lib.rs
  scylla-cql/src/serialize/batch.rs
  scylla-cql/src/serialize/mod.rs
  scylla-cql/src/serialize/row.rs
  scylla-cql/src/serialize/value.rs
  scylla-macros/src/from_row.rs
  scylla-macros/src/from_user_type.rs
  scylla-macros/src/into_user_type.rs
  scylla-macros/src/lib.rs
  scylla-macros/src/parser.rs
  scylla-macros/src/value_list.rs
  scylla/src/client/caching_session.rs
  scylla/src/client/pager.rs
  scylla/src/client/session.rs
  scylla/src/client/session_builder.rs
  scylla/src/client/session_test.rs
  scylla/src/cluster/worker.rs
  scylla/src/errors.rs
  scylla/src/lib.rs
  scylla/src/macros.rs
  scylla/src/response/legacy_query_result.rs
  scylla/src/response/mod.rs
  scylla/src/response/query_result.rs
  scylla/tests/integration/hygiene.rs
Labels: semver-checks-breaking

#1194 errors: rename and extract TracingError
  scylla/src/client/session.rs
  scylla/src/errors.rs
Labels: API-stability, semver-checks-breaking

#1191 errors: Narrow return error type of Session::[query/execute]_iter
  scylla/src/client/caching_session.rs
  scylla/src/client/pager.rs
  scylla/src/client/session.rs
  scylla/src/errors.rs
  scylla/src/network/connection.rs
Labels: API-stability, semver-checks-breaking

#1201 f_errors: remove unused variant from ColumnSpecParseErrorKind
  scylla-cql/src/frame/frame_errors.rs
Labels: API-stability, semver-checks-breaking

#1198 scylla_cql cleanup after legacy APIs removal
  docs/source/data-types/counter.md
  docs/source/data-types/date.md
  docs/source/data-types/decimal.md
  docs/source/data-types/duration.md
  docs/source/data-types/time.md
  docs/source/data-types/timestamp.md
  docs/source/data-types/timeuuid.md
  docs/source/migration-guides/0.11-serialization.md
  docs/source/queries/values.md
  examples/basic.rs
  examples/cql-time-types.rs
  examples/cqlsh-rs.rs
  examples/get_by_name.rs
  examples/query_history.rs
  examples/tower.rs
  scylla-cql/src/deserialize/row.rs
  scylla-cql/src/deserialize/value.rs
  scylla-cql/src/deserialize/value_tests.rs
  scylla-cql/src/frame/mod.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/frame/value_tests.rs
  scylla-cql/src/lib.rs
  scylla-cql/src/serialize/batch.rs
  scylla-cql/src/serialize/batch_tests.rs
  scylla-cql/src/serialize/row.rs
  scylla-cql/src/serialize/row_tests.rs
  scylla-cql/src/serialize/value.rs
  scylla-cql/src/serialize/value_tests.rs
  scylla-cql/src/value.rs
  scylla/src/client/caching_session.rs
  scylla/src/client/session_test.rs
  scylla/src/lib.rs
  scylla/src/observability/driver_tracing.rs
  scylla/src/observability/tracing.rs
  scylla/src/routing/locator/tablets.rs
  scylla/src/utils/pretty.rs
  scylla/tests/integration/cql_collections.rs
  scylla/tests/integration/cql_types.rs
  scylla/tests/integration/cql_value.rs
  scylla/tests/integration/history.rs
  scylla/tests/integration/hygiene.rs
Labels: semver-checks-breaking

#1202 Update RetryPolicy and SE terminology: "host" -> "target"
  scylla/src/client/pager.rs
  scylla/src/client/session.rs
  scylla/src/observability/history.rs
  scylla/src/policies/retry/default.rs
  scylla/src/policies/retry/downgrading_consistency.rs
  scylla/src/policies/retry/retry_policy.rs
  scylla/src/policies/speculative_execution.rs
  scylla/src/utils/test_utils.rs
  scylla/tests/integration/utils.rs
Labels: semver-checks-breaking

#1204 errors: final cleanups (restructure ExecutionError and introduce SchemaAgreementError)
  examples/schema_agreement.rs
  scylla-cql/src/frame/response/error.rs
  scylla/src/client/session.rs
  scylla/src/client/session_test.rs
  scylla/src/cluster/state.rs
  scylla/src/errors.rs
  scylla/src/network/connection.rs
  scylla/src/policies/load_balancing/default.rs
  scylla/src/policies/speculative_execution.rs
  scylla/src/response/request_response.rs
  scylla/src/statement/prepared_statement.rs
  scylla/src/utils/test_utils.rs
  scylla/tests/integration/batch.rs
Labels: API-stability, semver-checks-breaking

#1222 `partitioner`: Change visibility of `Partitioner`-related items
  scylla/benches/benchmark.rs
  scylla/src/client/pager.rs
  scylla/src/client/session_test.rs
  scylla/src/routing/partitioner.rs
  scylla/src/statement/prepared_statement.rs
Labels: semver-checks-breaking

#1231 Fix improper ip address formatting in CCM integration.
  scylla/tests/ccm_integration/ccm/ip_allocator.rs
Labels: semver-checks-breaking

#1249 Refactor `ColumnSpecs` and adjust `PreparedStatement` API
  scylla/src/client/pager.rs
  scylla/src/response/query_result.rs
  scylla/src/statement/prepared_statement.rs
  scylla/tests/integration/main.rs
  scylla/tests/integration/statement.rs
Labels: semver-checks-breaking

#1205 result: mark ColumnType and related enums as non-exhaustive
  scylla-cql/src/frame/response/result.rs
Labels: semver-checks-breaking

#1257 value: mark CqlValue as non_exhaustive
  Cargo.lock.msrv
  scylla-cql/Cargo.toml
  scylla-cql/src/lib.rs
  scylla-cql/src/pretty.rs
  scylla-cql/src/value.rs
  scylla/Cargo.toml
  scylla/src/cluster/metadata.rs
  scylla/src/network/connection_pool.rs
  scylla/src/observability/driver_tracing.rs
  scylla/src/utils/mod.rs
  scylla/src/utils/pretty.rs
Labels: API-breaking, API-stability, semver-checks-breaking
