Repository scylladb/scylla-rust-driver, pull requests merged in 2025-01, with the labels that each got.

#1168 errors: rename RequestError and make it private
  scylla/src/errors.rs
  scylla/src/network/connection.rs
Labels: semver-checks-breaking

#1157 session: internal request execution API error types refactor
  scylla/src/client/pager.rs
  scylla/src/client/session.rs
  scylla/src/client/session_test.rs
  scylla/src/cluster/metadata.rs
  scylla/src/errors.rs
  scylla/src/network/connection.rs
  scylla/src/policies/load_balancing/default.rs
  scylla/src/policies/load_balancing/mod.rs
  scylla/src/policies/retry/default.rs
  scylla/src/policies/retry/downgrading_consistency.rs
  scylla/src/policies/retry/fallthrough.rs
  scylla/src/policies/retry/mod.rs
  scylla/src/policies/retry/retry_policy.rs
  scylla/src/response/request_response.rs
  scylla/tests/integration/execution_profiles.rs
Labels: semver-checks-breaking

#1159 errors: narrow error types accepted by `HistoryListener`
  scylla/src/client/pager.rs
  scylla/src/client/session.rs
  scylla/src/errors.rs
  scylla/src/observability/history.rs
  scylla/src/policies/speculative_execution.rs
  scylla/tests/integration/history.rs
Labels: API-stability, semver-checks-breaking

#1160 errors: pager API errors refactor
  scylla/src/client/pager.rs
  scylla/src/client/session.rs
  scylla/src/cluster/metadata.rs
  scylla/src/network/connection.rs
  scylla/src/statement/batch.rs
  scylla/src/statement/prepared_statement.rs
Labels: API-stability, semver-checks-breaking

#1128 Implement timestamp generators
  docs/source/SUMMARY.md
  docs/source/queries/queries.md
  docs/source/queries/timestamp-generators.md
  scylla/src/client/session.rs
  scylla/src/client/session_builder.rs
  scylla/src/client/session_test.rs
  scylla/src/network/connection.rs
  scylla/src/policies/mod.rs
  scylla/src/policies/timestamp_generator.rs
Labels: enhancement

#1181 errors: adjust ShardingError
  scylla/src/network/connection.rs
  scylla/src/routing/mod.rs
  scylla/src/routing/sharding.rs
Labels: API-stability, semver-checks-breaking

#1166 Remove CqlType in favor of ColumnType
  scylla-cql/benches/benchmark.rs
  scylla-cql/src/deserialize/mod.rs
  scylla-cql/src/deserialize/result.rs
  scylla-cql/src/deserialize/row_tests.rs
  scylla-cql/src/deserialize/value.rs
  scylla-cql/src/deserialize/value_tests.rs
  scylla-cql/src/frame/frame_errors.rs
  scylla-cql/src/frame/request/mod.rs
  scylla-cql/src/frame/response/result.rs
  scylla-cql/src/frame/value_tests.rs
  scylla-cql/src/serialize/row.rs
  scylla-cql/src/serialize/value.rs
  scylla-cql/src/types_tests.rs
  scylla-macros/src/deserialize/value.rs
  scylla-macros/src/serialize/value.rs
  scylla/benches/benchmark.rs
  scylla/src/client/session_test.rs
  scylla/src/cluster/metadata.rs
  scylla/src/lib.rs
  scylla/src/response/legacy_query_result.rs
  scylla/src/response/query_result.rs
  scylla/src/routing/locator/tablets.rs
  scylla/src/statement/prepared_statement.rs
  scylla/src/utils/parse.rs
  scylla/src/utils/pretty.rs
  scylla/tests/integration/cql_value.rs
  scylla/tests/integration/hygiene.rs
Labels: API-stability, semver-checks-breaking

#1179 cicd: fix authenticate tests
  .github/workflows/authenticate_test.yml
  test/cluster/docker-compose-passauth.yml
Labels: symptom/ci stability

#1170 errors: metadata errors refactor
  scylla/src/client/session.rs
  scylla/src/cluster/metadata.rs
  scylla/src/cluster/worker.rs
  scylla/src/errors.rs
Labels: API-stability, semver-checks-breaking

#1180 errors: refactor errors on USE KEYSPACE execution path and clean up NewSessionError
  scylla/src/client/session.rs
  scylla/src/client/session_test.rs
  scylla/src/cluster/node.rs
  scylla/src/cluster/worker.rs
  scylla/src/errors.rs
  scylla/src/network/connection.rs
  scylla/src/network/connection_pool.rs
Labels: API-stability, semver-checks-breaking

#1185 errors: rename `QueryError` to `ExecutionError`
  docs/source/queries/schema-agreement.md
  docs/source/queries/timeouts.md
  examples/schema_agreement.rs
  examples/tower.rs
  scylla/src/client/caching_session.rs
  scylla/src/client/session.rs
  scylla/src/client/session_test.rs
  scylla/src/cluster/state.rs
  scylla/src/errors.rs
  scylla/src/network/connection.rs
  scylla/src/response/request_response.rs
  scylla/src/statement/batch.rs
  scylla/src/statement/prepared_statement.rs
  scylla/src/utils/test_utils.rs
  scylla/tests/integration/batch.rs
  scylla/tests/integration/large_batch_statements.rs
  scylla/tests/integration/tablets.rs
  scylla/tests/integration/utils.rs
Labels: API-stability, semver-checks-breaking
