Repository scylladb/scylla-rust-driver, pull requests merged in 2025-07, with the labels that each got.

#1385 statements: expose API to unset (serial) consistency
  scylla/src/cluster/control_connection.rs
  scylla/src/statement/batch.rs
  scylla/src/statement/prepared.rs
  scylla/src/statement/unprepared.rs
Labels: enhancement

#1393 codewide: rename Scylla -> ScyllaDB
  .github/workflows/rust.yml
  CONTRIBUTING.md
  MAINTENANCE.md
  README.md
  docs/book.toml
  docs/source/SUMMARY.md
  docs/source/conf.py
  docs/source/connecting/connecting.md
  docs/source/data-types/udt.md
  docs/source/index.md
  docs/source/load-balancing/default-policy.md
  docs/source/quickstart/quickstart.md
  docs/source/quickstart/scylla-docker.md
  docs/source/retry-policy/downgrading-consistency.md
  docs/source/statements/lwt.md
  docs/source/tracing/tracing.md
  scylla/src/client/self_identity.rs
  scylla/src/client/session.rs
  scylla/src/client/session_builder.rs
  scylla/src/cloud/config.rs
  scylla/src/cluster/node.rs
  scylla/src/network/connection_pool.rs
  scylla/src/network/mod.rs
  scylla/src/routing/locator/tablets.rs
  scylla/src/routing/locator/token_ring.rs
  scylla/src/routing/mod.rs
  scylla/src/routing/partitioner.rs
  scylla/src/routing/sharding.rs
  scylla/src/utils/test_utils.rs
  scylla/tests/integration/ccm/lib/cluster.rs
Labels: area/documentation

#1397 serialize: support `Bytes` -> CQL `blob` conversion
  docs/source/data-types/blob.md
  docs/source/data-types/data-types.md
  scylla-cql/src/serialize/value.rs
  scylla-cql/src/serialize/value_tests.rs
Labels: enhancement, area/serialization

#1401 Fix plan exhaustion handling in SE and introduce SE unit tests.
  scylla/src/policies/speculative_execution.rs
Labels: area/statement-execution

#1400 scylla: Write missing docstrings
  scylla-cql/benches/benchmark.rs
  scylla/Cargo.toml
  scylla/benches/benchmark.rs
  scylla/src/authentication/mod.rs
  scylla/src/client/caching_session.rs
  scylla/src/client/self_identity.rs
  scylla/src/client/session.rs
  scylla/src/client/session_builder.rs
  scylla/src/cloud/config.rs
  scylla/src/cloud/mod.rs
  scylla/src/cluster/metadata.rs
  scylla/src/cluster/node.rs
  scylla/src/cluster/state.rs
  scylla/src/errors.rs
  scylla/src/lib.rs
  scylla/src/network/tls.rs
  scylla/src/observability/history.rs
  scylla/src/observability/metrics.rs
  scylla/src/observability/tracing.rs
  scylla/src/policies/address_translator.rs
  scylla/src/policies/load_balancing/mod.rs
  scylla/src/policies/load_balancing/plan.rs
  scylla/src/policies/load_balancing/single_target.rs
  scylla/src/policies/retry/default.rs
  scylla/src/policies/retry/downgrading_consistency.rs
  scylla/src/policies/retry/fallthrough.rs
  scylla/src/policies/retry/mod.rs
  scylla/src/policies/speculative_execution.rs
  scylla/src/policies/timestamp_generator.rs
  scylla/src/response/query_result.rs
  scylla/src/routing/locator/mod.rs
  scylla/src/routing/mod.rs
  scylla/src/routing/partitioner.rs
  scylla/src/routing/sharding.rs
  scylla/src/statement/batch.rs
  scylla/src/statement/prepared.rs
  scylla/src/statement/unprepared.rs
  scylla/tests/integration/main.rs
Labels: area/documentation
